apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapiapp.fullname" . }}-movie-db-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.database.movie.password | b64enc }}
  DATABASE_URI: {{ printf "postgresql://%s:%s@%s-movie-db/%s" .Values.database.movie.user .Values.database.movie.password (include "fastapiapp.fullname" .) .Values.database.movie.name | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapiapp.fullname" . }}-cast-db-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.database.cast.password | b64enc }}
  DATABASE_URI: {{ printf "postgresql://%s:%s@%s-cast-db/%s" .Values.database.cast.user .Values.database.cast.password (include "fastapiapp.fullname" .) .Values.database.cast.name | b64enc }}