apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapiapp.fullname" . }}-movie-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "fastapiapp.name" . }}-movie-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapiapp.fullname" . }}-cast-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ include "fastapiapp.name" . }}-cast-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapiapp.fullname" . }}-nginx
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ include "fastapiapp.name" . }}-nginx
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}