apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapiapp.fullname" . }}-movie-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: {{ include "fastapiapp.name" . }}-movie-db
  clusterIP: None # Headless service for StatefulSet

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fastapiapp.fullname" . }}-cast-db
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    app: {{ include "fastapiapp.name" . }}-cast-db
  clusterIP: None # Headless service for StatefulSet