apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fastapiapp.fullname" . }}-movie-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "movie-db"
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fastapiapp.name" . }}-movie-db
  template:
    metadata:
      labels:
        app: {{ include "fastapiapp.name" . }}-movie-db
    spec:
      containers:
      - name: movie-db
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: {{ include "fastapiapp.fullname" . }}-movie-db-configmap
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fastapiapp.fullname" . }}-movie-db-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "fastapiapp.fullname" . }}-cast-db
  namespace: {{ .Values.namespace }}
spec:
  serviceName: "cast-db"
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "fastapiapp.name" . }}-cast-db
  template:
    metadata:
      labels:
        app: {{ include "fastapiapp.name" . }}-cast-db
    spec:
      containers:
      - name: cast-db
        image: postgres:12.1-alpine
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: {{ include "fastapiapp.fullname" . }}-cast-db-configmap
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "fastapiapp.fullname" . }}-cast-db-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi